version: "3.9"

services:
  ransomshield-api:
    build: .
    container_name: ransomshield
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
